tbonlineproject/faq/urls.py
from django.conf.urls.defaults import *
from django.views.generic import ListView, DetailView

from faq.models import QuestionCategory, QuestionAndAnswer

urlpatterns = patterns('faq.views',
    url(r'^$', ListView.as_view(model=QuestionCategory,
                            context_object_name="questioncategory_list",),
                            name='list_faq'),
    url(r'category/(?P<pk>\d+)/$', DetailView.as_view(model=QuestionCategory,
                            context_object_name="questioncategory",),
                            name='detail_faq_category'),
)

tbonlineproject/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps import FlatPageSitemap

from filebrowser.sites import site as filebrowser_site

from contact_form.views import contact_form

from post.views import PublishedFrontPagePostsView

from post.forms import EnhancedContactForm
from post.sitemap import PostSitemap
from story.sitemap import StorySitemap
from gallery.sitemap import ImageSitemap

admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
    'post': PostSitemap,
    'story': StorySitemap,
    'image': ImageSitemap
}

urlpatterns = patterns('',
    # Examples:
    url(r'^$', PublishedFrontPagePostsView.as_view(template_name='index.html'),
        name='home'),
    (r'^archive/', include('archive.urls')),
    (r'^posts/', include('post.urls')),
    (r'^galleries/', include('gallery.urls')),
    (r'^stories/', include('story.urls')),
    (r'^feeders/', include('feeder.urls')),
    (r'^comments/', include('CommentRecaptcha.urls')),
    (r'^accounts/', include('RegistrationRecaptcha.urls')),
    (r'^faq/', include('faq.urls')),
    (r'^search/', include('haystack.urls')),
    (r'^notifications/', include('notifications.urls')),
    (r'^tags/', include('tagviews.urls')),
    (r'^tb/', include('tb.urls')),
    # url(r'^contact/$', contact_form, {'form_class': EnhancedContactForm}, name='contact'),
    # (r'^contact/', include('contact_form.urls')),
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),

    (r'^grappelli/', include('grappelli.urls')),
    (r'^admin/filebrowser/', include(filebrowser_site.urls)),
    (r'^profile/', include('userprofiles.urls')),



    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
    )
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

tbonlineproject/faq/models.py
from django.db import models
from django.utils.translation import ugettext as _

# Create your models here.

class QuestionCategory(models.Model):
    '''Each question and answer is assigned to an instance of thise model.
    '''
    name = models.CharField(max_length=200, unique=True)
    description = models.TextField(blank=True)
    last_modified = models.DateTimeField(auto_now=True, editable=False)
    date_added = models.DateTimeField(auto_now_add=True, editable=False)

    def __unicode__(self):
        return self.name
    
    class Meta:
        verbose_name = _('question and answer category')
        verbose_name_plural = _('question and answer categories')
        ordering = ['last_modified',]
        
class QuestionAndAnswer(models.Model):
    '''Represents one question and its answer, assigned to a category.
    '''
    category = models.ForeignKey(QuestionCategory)
    question = models.TextField()
    answer = models.TextField(blank=True)
    position = models.PositiveIntegerField(default=0)
    last_modified = models.DateTimeField(auto_now=True, editable=False)
    date_added = models.DateTimeField(auto_now_add=True, editable=False)
    
    def __unicode__(self):
        return self.question
    
    class Meta:
        verbose_name = _('question and answer')
        verbose_name_plural = _('questions and answers')        
        ordering = ['category', 'position',]        

tbonlineproject/faq/views.py
# Create your views here.

tbonlineproject/faq/templates/faq/questioncategory_detail.html
{% extends 'base.html' %}
{% load url from future %}
{% load i18n %}

{% block title %}{{block.super}} - {{ questioncategory.name }}{% endblock %}

{% block content %}

<h1>{{ questioncategory.name }}</h1>

<ol class="questions">
{% for question in questioncategory.questionandanswer_set.all %}
    <li><a name="question_{{forloop.counter}}" href="#answer_{{question.pk}}">{{question.question|safe}}</a></li>
{% empty %}
    <p>{% trans "There are no questions in this category yet." %}</p>
{% endfor %} 
</ol>

<div class="questions-and-answers">
{% for question in questioncategory.questionandanswer_set.all %}

    <div class="question"><a href="#question_{{forloop.counter}}" name="answer_{{question.pk}}">{{forloop.counter}}.</a> {{question.question|safe}}</div>
    
    <div class="answer">{{question.answer|safe|linebreaks|urlize}}</div>    
    
{% empty %}
    <p>{% trans "There are no questions in this category yet." %}</p>
{% endfor %} 
</div>

{% endblock %}

tbonlineproject/faq/templates/faq/questioncategory_list.html
{% extends 'base.html' %}
{% load url from future %}
{% load i18n %}

{% block title %}{{block.super}} - {% trans "Question and answer categories" %}{% endblock %}

{% block content %}

<h1>{% trans "Question and answer categories" %}</h1>

<ul class="question-category">
{% for category in questioncategory_list %}
    <li><a href="{% url 'detail_faq_category' category.pk %}">{{category.name}}</a></li>
{% empty %}
    <p>{% trans "There are no question and answer categories yet." %}</p>
{% endfor %} 
</ul>
{% endblock %}